### PR TITLE
merge 2 bitbucket entries

### PR DESCRIPTION
**Pull request by bithakr**

### CODE REVIEW

**Comment by AchoArnold** [comment]
Thanks 👍

**Comment by bithakr** [comment]
Did you mean to merge this?

**Comment by AchoArnold** [comment]
Indeed. I can't seem to find the merge button anymore sorry @bithakr

**Comment by bithakr** [comment]
@AchoArnold the merge button is gone b/c other PRs since have cause a conflict. I will res PR

**Pull request closed without merging**
