### PR TITLE
Dashlane Password Manager

### PR DESCRIPTION
**Pull request by chintogtokh**

### CODE REVIEW

**Comment by AchoArnold** [comment]
Hey @chintogtokh

Thanks for the PR. Please can you resolve the conflict? Please add this new item at the end of the list. If you feel like typing more, Please sort the list  of password managers in alphabetical order 😉

**Comment by chintogtokh** [comment]
@AchoArnold No worries, done :)

**Comment by chintogtokh** [comment]
@AchoArnold No worries, done :)

**Comment by AchoArnold** [comment]
Gracias @chintogtokh

**Pull request merged**
