### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Verkiya**
Kindly look through the ammendments made , whether they're upto mark or not and correct me if i'm wrong somewhere.
Thanks :)

### CODE REVIEW

**Comment by AchoArnold** [comment]
Hello @Verkiya 

Thanks for the PR, I would love that beside each software, You should write the actual educational discount provided e.g Write

* [ShiftEdit](https://shiftedit.net/) - ShiftEdit is a powerful online IDE for developing websites. Get 50 Education Licences for only $750 per year.

**Instead of** 

* [ShiftEdit](https://shiftedit.net/) - ShiftEdit is a powerful online IDE for developing websites.Education Discount available for Students.

**Comment by Verkiya** [comment]
@AchoArnold  Ok sir, I didn't know that.I'll take care of it next time. :)

**Comment by AchoArnold** [comment]
Hello @Verkiya  I see you added more discounts. But like i mentioned before, Please beside each software, Add the discount provided and not just what the software does.

**Comment by AchoArnold** [comment]
Thanks @Verkiya

**Pull request merged**
